export const ActionTypes = {
  GET_BOARDS: "GET_BOARDS",
  CREATE_BOARD: "CREATE_BOARD",
  GET_LISTS: "GET_LISTS",
  ADD_LIST: "ADD_LIST",
  ARCHIVE_LIST: "ARCHIVE_LIST",
  GET_CARDS: "GET_CARDS",
  ADD_CARD: "ADD_CARD",
  DELETE_CARD: "DELETE_CARD",
};
